services:
  # PostgreSQL database for storing weather data
  postgres:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    networks:
      - airflow_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # DBeaver for visual management of PostgreSQL

  # Apache Airflow for scheduling and ETL Logic
  airflow:
    image: apache/airflow:3.3.2
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Airflow settings
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: "True"
      AIRFLOW__API__WORKERS: 1
      AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW_JWT_SECRET}
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      # Used by the ETL DAG
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    volumes:
      - ./dags:/opt/airflow/dags:ro
    ports:
      - "127.0.0.1:${AIRFLOW_PORT:-8080}:8080"
    command: standalone
    networks:
      - airflow_net

volumes:
  postgres_data:

networks:
  airflow_net:
